version: '3'

networks:
  nginx_proxy_network:
    external:
      name: nginx_proxy_network

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    restart: "always"
    networks:
      - nginx_proxy_network
    environment:
      VIRTUAL_HOST: eshopio.app
      VIRTUAL_HOST_ALIAS: www.eshopio.app
      LETSENCRYPT_HOST: eshopio.app,www.eshopio.app
    volumes:
      # PHP Configs
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      #- ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro

      # Application
      - ./app:/var/www/html/app:cached
      - ./assets/dynamic:/var/www/html/assets/dynamic:cached
      - ./assets/static:/var/www/html/assets/static:cached
      - ./www:/var/www/html/www:cached
      - ./log:/var/www/html/log:cached
      - ./temp:/var/www/html/temp:cached
      - ./vendor:/var/www/html/vendor:cached
      - ./.htaccess:/var/www/html/.htaccess:cached